import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

export const seed = async (knex: Knex) => {
    const [{ count }] = await knex(ETableNames.cidade).count<[{count: number}]>("* as count");

    // se ja tiver registros no banco de dados, não roda a mseed
    if (!Number.isInteger(count) || Number(count) > 0) return;

    const cidadesToInsert = cidadesAleatorias.map(nomeDeCidades => ({nome: nomeDeCidades}));
    await knex(ETableNames.cidade).insert(cidadesToInsert);
};

const cidadesAleatorias = [
    "Rafael Godeiro",
    "Riacho da Cruz",
    "Tibau do Sul",
    "Jardim do Seridó",
    "Caiçara do Norte",
    "Jundiá",
    "Vila Flor",
    "Tenente Laurentino Cruz",
    "São Vicente",
    "São Bento do Norte",
    "Serrinha dos Pintos",
    "Barcelona",
    "Serra Caiada",
    "São Tomé",
    "Venha-Ver",
    "Pendências",
    "Ruy Barbosa",
    "Messias Targino",
    "Tibau",
    "Governador Dix-Sept Rosado",
    "Jucurutu",
    "Bento Fernandes",
    "Maxaranguape",
    "Caraúbas",
    "Carnaúba dos Dantas",
    "Fernando Pedroza",
    "Lajes",
    "São Francisco do Oeste",
    "Galinhos",
    "Nísia Floresta",
    "São Miguel do Gostoso",
    "Montanhas",
    "Riachuelo",
    "Pedra Grande",
    "Olho-d'Água do Borges",
    "Parnamirim",
    "João Dias",
    "Bodó",
    "Almino Afonso",
    "Ielmo Marinho",
    "Jandaíra",
    "Frutuoso Gomes",
    "Ceará-Mirim",
    "Coronel João Pessoa",
    "Baraúna",
    "Itaú",
    "Passa e Fica",
    "Lagoa de Pedras",
    "Portalegre",
    "São Rafael",
    "Canguaretama",
    "Touros",
    "Tangará",
    "Upanema",
    "Sítio Novo",
    "São João do Sabugi",
    "São José do Campestre",
    "Jardim de Angicos",
    "Ipueira",
    "São Paulo do Potengi",
    "Riacho de Santana",
    "Jardim de Piranhas",
    "Bom Jesus",
    "Lagoa de Velhos",
    "Brejinho",
    "Santa Cruz",
    "Japi",
    "Pedro Velho",
    "João Câmara",
    "Lagoa Salgada",
    "Caicó",
    "Santo Antônio",
    "São José de Mipibu",
    "Santa Maria",
    "Cruzeta",
    "Currais Novos",
    "Goianinha",
    "Macau",
    "Cerro Corá",
    "Patu",
    "Monte das Gameleiras",
    "Januário Cicco",
    "Rafael Fernandes",
    "Pilões",
    "Poço Branco",
    "São Fernando",
    "São José do Seridó",
    "Apodi",
    "Barcelona",
    "Encanto",
    "Pau dos Ferros",
    "Caraúbas",
    "Touros",
    "Água Nova",
    "Riachuelo",
    "Almino Afonso",
    "Caiçara do Rio do Vento",
    "Brejinho",
    "Ruy Barbosa",
    "Paraú",
    "Serra Negra do Norte",
    "São Tomé",
    "Sítio Novo",
    "São Vicente",
    "Espírito Santo",
    "Pedro Avelino",
    "Vila Flor",
    "Lagoa d'Anta",
    "Caraúbas",
    "Pureza",
    "Senador Elói de Souza",
    "Barcelona",
    "Bento Fernandes",
    "Viçosa",
    "Governador Dix-Sept Rosado",
    "Passagem",
    "Nísia Floresta",
    "Riacho da Cruz",
    "Jardim de Angicos",
    "Lagoa de Velhos",
    "Pendências",
    "Santo Antônio",
    "Parazinho",
    "Lajes Pintadas",
    "São Rafael",
    "Lagoa Salgada",
    "Tangará",
    "Taipu",
    "Ceará-Mirim",
    "São Bento do Norte",
    "Serra Caiada",
    "Ipanguaçu",
    "Jundiá",
    "São Francisco do Oeste",
    "Carnaúba dos Dantas",
    "Lajes",
    "Pau dos Ferros",
    "Pedra Preta",
    "Rafael Godeiro",
    "São José de Mipibu",
    "Galinhos",
    "São Gonçalo do Amarante",
    "Monte das Gameleiras",
    "Jaçanã",
    "Monte Alegre",
    "São Paulo do Potengi",
    "Baraúna",
    "Ipueira",
    "Serra de São Bento",
    "João Câmara",
    "Serrinha",
    "São José do Seridó",
    "São Miguel do Gostoso",
    "Cruzeta",
    "Maxaranguape",
    "Tibau",
    "Riacho de Santana",
    "Rodolfo Fernandes",
    "Coronel Ezequiel",
    "Tibau do Sul",
    "Viçosa",
    "Messias Targino",
    "Venha-Ver",
    "Jardim do Seridó",
    "Nova Cruz",
    "Pedro Velho",
    "Cerro Corá",
    "Afonso Bezerra",
    "Frutuoso Gomes",
    "Felipe Guerra",
    "Japi",
    "São José do Campestre",
    "São Pedro",
    "Caiçara do Norte",
    "São Miguel",
    "Campo Redondo",
    "Pedro Avelino",
    "Montanhas",
    "São Fernando",
    "Jardim de Piranhas",
    "São Tomé",
    "Alto do Rodrigues",
    "Lagoa de Pedras",
    "Boa Saúde",
    "Carnaubais",
    "Paraíso",
    "Ipanguaçu",
    "Canguaretama",
    "Parelhas",
    "Upan"
];

  